DaoVietAnh.Asm2.Web/Pages/Pizza/Manage.cshtml.cs
using DaoVietAnh.Asm2.Repo.DTO;
using DaoVietAnh.Asm2.Repo.Payload.Request;
using DaoVietAnh.Asm2.Repo.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DaoVietAnh.Asm2.Web.Pages.Pizza
{
    public class ManageModel : PageModel
    {
        public int PageNumber { get; set; } = 1;
        public int PageSize { get; set; } = 10;
        public int TotalCount { get; set; } = 15;
        public List<PizzaDTO>? PizzaDTOs;
        private IPizzaService _pizzaService;

        public ManageModel(IPizzaService pizzaService)
        {
            _pizzaService = pizzaService;
        }

        public async Task OnGet()
        {
            var result = await Task.Run(() =>
                _pizzaService.GetAllPizzas(new PizzaServicePagingRequest()
                {
                    PageNumber = PageNumber,
                    PageSize = PageSize
                })
            );
            PizzaDTOs = (List<PizzaDTO>)result.ReturnData!;
        }
        public IActionResult OnPostDeletePizza(int id)
        {
            var result = _pizzaService.Delete(id);
            return RedirectToPage("/Pizza/Manage");
        }
        public IActionResult OnPostUpdatePizza(int pizzaId)
        {
            return RedirectToPage("/Pizza/Update", new { pizzaId = pizzaId });        
        }
    }
}

DaoVietAnh.Asm2.Web/Pages/Staff/Manage.cshtml.cs
using DaoVietAnh.Asm2.Repo.DTO;
using DaoVietAnh.Asm2.Repo.Payload.Request;
using DaoVietAnh.Asm2.Repo.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DaoVietAnh.Asm2.Web.Pages.Member
{
    public class ManageModel : PageModel
    {
        public int PageNumber { get; set; } = 1;
        public int PageSize { get; set; } = 10;
        public int TotalCount { get; set; } = 15;
        public List<MemberDTO>? MemberDTOs;
        private IMemberService _memberService;

        public ManageModel(IMemberService memberService)
        {
            _memberService = memberService;
        }

        public async Task OnGet()
        {
            var result = await Task.Run(() =>
                _memberService.GetMembers()
            );
            MemberDTOs = (List<MemberDTO>)result.ReturnData!;
        }      
    }
}

DaoVietAnh.Asm2.Web/Pages/Staff/Manage.cshtml
@page
@using DaoVietAnh.Asm2.Repo.DTO
@using Newtonsoft.Json
@model Member.ManageModel
@Html.AntiForgeryToken()

@{
    AccountDTO? accountDTO = null!;
    GetLoggedInAccount();
}
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="Scripts/bootstrap.js"></script>
    <script src="Scripts/bootstrap.min.js"></script>
</head>
<body>
    @if (IsStaff())
    {
        <div class="container margin-top-from-navbar">
            <h1 class="display-5 mb-5">Member Management</h1>

            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">No.</th>
                        <th scope="col">Username</th>
                        <th scope="col">Full Name</th>
                        <th scope="col">Type</th>
                        <th scope="col">Options</th>

                    </tr>
                </thead>
                <tbody>
                    @{
                        int no = 1;
                        foreach (MemberDTO memberDTO in Model.MemberDTOs!)
                        {
                            <tr>
                                <th scope="row">@no</th>
                                <td>@memberDTO.Username</td>
                                <td>@memberDTO.FullName</td>
                                <td>@memberDTO.Type</td>
                                <td>
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            Action
                                        </button>
                                        <div class="dropdown-menu">
                                            <form method="post">
                                                <input type="hidden" name="memberId" value="@memberDTO.MemberId" />
                                                <button class="dropdown-item" asp-page-handler="UpdatePizza" type="submit">Update</button>
                                            </form>
                                            <!-- Button trigger modal
                                            Here, data-target triggers the Modal.
                                            -->
                                            <button class="dropdown-item" data-bs-toggle="modal"
                                                    data-bs-target="#confirmDeleteModal" data-member-id="@memberDTO.MemberId">
                                                Delete
                                            </button>

                                        </div>
                                    </div>
                                </td>
                                @Html.AntiForgeryToken()
                            </tr>
                            no++;
                        }
                    }

                </tbody>
            </table>
            <div class="mt-5">
                <ul class="pagination">
                    @for (var i = 1; i <= Model.TotalCount; i++)
                    {
                        <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                            <a class="page-link" href="?pageNumber=@i">@i</a>
                        </li>

                    }
                </ul>
            </div>
        </div>

    }
    else
    {
        HttpContext.Response.Redirect("/");
    }
    <div class="modal fade" id="confirmDeleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Confirm delete</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Do you really want to delete this Pizza? This action is irreversible!
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" id="confirmDeleteButton" onclick="$('#confirmDeleteModal').modal('hide');">
                        Yes
                    </button>
                    <button type="button" class="btn btn-secondary" onclick="$('#confirmDeleteModal').modal('hide');">No</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Delete Success Modal -->
    <div class="modal fade" id="deleteSuccessModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Info</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    <span aria-hidden="true">&times;</span>
                </div>
                <div class="modal-body">
                    The pizza was successfully deleted.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" onclick="$('#deleteSuccessModal').modal('hide');">Ok</button>
                </div>
            </div>
        </div>
    </div>


</body>



<!-- Delete Pizza AJAX Script. Runs when the Delete Modal is shown.-->
<script>
    $(document).ready(function () {
        $('#confirmDeleteModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget); // Button that triggered the modal
            var memberId = button.data('member-id'); // Extract pizza ID from data attribute
            var modal = $(this);
            console.log("Selected Pizza Id: " + memberId);

            // When confirm button in modal is clicked
            modal.find('#confirmDeleteButton').on('click', function () {
                // Send AJAX request to backend with pizza ID
                console.log("Delete button is clicked!")
                $.ajax({
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("XSRF-TOKEN",
                            $('input:hidden[name="__RequestVerificationToken"]').val());
                    },
                    url: "?handler=DeletePizza",
                    type: 'POST',
                    data: { id: memberId },
                    success: function (data) {
                        $('#deleteSuccessModal').modal('show');
                    },
                    error: function (xhr, status, error) {
                        console.log(status)
                        console.log(error)
                    }
                });
            });
        });
    });
    $(document).ready(function () {
        $('#deleteSuccessModal').on('hidden.bs.modal', function (e) {
            location.reload();
        });
    });
</script>
@{
    void GetLoggedInAccount()
    {
        string accountFromSession = HttpContext.Session.GetString("account")!;
        if (accountFromSession != null)
            accountDTO = JsonConvert.DeserializeObject<AccountDTO>(accountFromSession)!;
    }
    bool IsStaff()
    {
        if (accountDTO != null && accountDTO.Type!.Equals("1")) return true;
        return false;
    }

}