DaoVietAnh.Asm2.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace DaoVietAnh.Asm2.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

DaoVietAnh.Asm2.Web/Pages/Index.cshtml.cs
using DaoVietAnh.Asm2.Repo.Payload.Request;
using DaoVietAnh.Asm2.Repo.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DaoVietAnh.Asm2.Web.Pages
{
    public class IndexModel : PageModel
    {

        [BindProperty]
        public GetPizzasByRequest? GetPizzasByRequest { get; set; }
        public int PageNumber { get; set; } = 1;
        public int PageSize { get; set; } = 10;
        public int TotalCount { get; set; } = 15;

        private readonly IPizzaService _pizzaService;

        public IndexModel(IPizzaService pizzaService)

        {
            _pizzaService = pizzaService;
        }

        public async Task OnGetAsync(int pageNumber)
        {
            var pizzaServiceResult = await _pizzaService.GetAllPizzas(
                new PizzaServicePagingRequest()
                {
                    PageNumber = pageNumber,
                    PageSize = PageSize
                }
            );
            ViewData["Pizzas"] = pizzaServiceResult.ReturnData;
        }
        public IActionResult OnPostShowDetails(int pizzaId)
        {
            return RedirectToPage("/Pizza/Details", new { pizzaId = pizzaId });
        }
        public async Task<IActionResult> OnPostGetBy()
        {
            var pizzaServiceResult = await _pizzaService.GetPizzasBy(GetPizzasByRequest!);
            ViewData["Pizzas"] = pizzaServiceResult.ReturnData;
            return Page();
        }
    }
}

DaoVietAnh.Asm2.Web/Pages/Index.cshtml
@page
@using DaoVietAnh.Asm2.Repo.DTO
@using Newtonsoft.Json

@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<div class="container margin-top-from-navbar">
    <div class="row mb-3">
        <div class="col-3">
            <div class="text-left">
                <h1 class="display-5">Our Offers</h1>
            </div>
        </div>
        <div class="justify-content-end">
            <div class="container mt-3">
                <form method="post">
                    <div class="row">
                        <div class="col-5">
                            <input asp-for="@Model.GetPizzasByRequest!.Value" type="text" class="form-control" placeholder="Search for pizza...">
                        </div>
                        @* <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">Search by...</button> *@
                        <div class="col-3">
                            <select asp-for="@Model.GetPizzasByRequest!.Option" class="form-select">
                                <option value="NAME">Name</option>
                                <option value="ID">ID</option>
                                <option value="UNIT_PRICE">Unit Price</option>
                            </select>
                        </div>
                        <div class="col-1">
                            <button asp-page-handler="GetBy" class="btn btn-primary" type="submit">Search</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>


    <div>
        @{
            var pizzas = ViewData["Pizzas"];
            if (pizzas == null)
            {
                <div> Loading</div>
            }
            else
            {
                <div class="row">
                    @foreach (var pizza in (List<PizzaDTO>)ViewData["Pizzas"]!)
                    {
                        <div class="card custom-margin" style="width: 16rem; height:25rem">
                            <img src="@pizza.Image" width="500" height="200" class="card-img-top mt-2" alt="...">
                            <div class="card-body">
                                <h3 class="card-title mb-1">@pizza.Name</h3>
                                <h6 class="card-subtitle mb-1">Category: @pizza.Category</h6>
                                <h5 class="card-subtitle mb-1">$@pizza.Price</h5>
                            </div>
                            <form method="post" asp-page-handler="ShowDetails">
                                <input type="hidden" name="pizzaId" value="@pizza.Id" />
                                <button class="btn btn-primary mb-2" type="submit">Details</button>
                            </form>
                        </div>


                    }

                </div>
            }
        }
    </div>
    <div class="mt-5">
        <ul class="pagination">
            @for (var i = 1; i <= Model.TotalCount; i++)
            {
                <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                    <a class="page-link" href="?pageNumber=@i">@i</a>
                </li>

            }
        </ul>
    </div>

</div>